// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v3.2.16
// 	protoc        v3.2.16
// source: nucleuspb/state.proto

package nucleuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proposal mirrors the VSB pending-action struct from watcher.go.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_nucleuspb_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_nucleuspb_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_nucleuspb_state_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// HoveredUnit mirrors the Mmap hovered-unit layout.
type HoveredUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UnitType      string                 `protobuf:"bytes,3,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	ImgPath       string                 `protobuf:"bytes,4,opt,name=img_path,json=imgPath,proto3" json:"img_path,omitempty"`
	X             float32                `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoveredUnit) Reset() {
	*x = HoveredUnit{}
	mi := &file_nucleuspb_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoveredUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoveredUnit) ProtoMessage() {}

func (x *HoveredUnit) ProtoReflect() protoreflect.Message {
	mi := &file_nucleuspb_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoveredUnit.ProtoReflect.Descriptor instead.
func (*HoveredUnit) Descriptor() ([]byte, []int) {
	return file_nucleuspb_state_proto_rawDescGZIP(), []int{1}
}

func (x *HoveredUnit) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HoveredUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HoveredUnit) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *HoveredUnit) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

func (x *HoveredUnit) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HoveredUnit) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// NucleusState is the VSB snapshot broadcast to all Nucleus Deck clients at ~60fps.
type NucleusState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposal      *Proposal              `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	HoveredUnit   *HoveredUnit           `protobuf:"bytes,3,opt,name=hovered_unit,json=hoveredUnit,proto3" json:"hovered_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NucleusState) Reset() {
	*x = NucleusState{}
	mi := &file_nucleuspb_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NucleusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NucleusState) ProtoMessage() {}

func (x *NucleusState) ProtoReflect() protoreflect.Message {
	mi := &file_nucleuspb_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NucleusState.ProtoReflect.Descriptor instead.
func (*NucleusState) Descriptor() ([]byte, []int) {
	return file_nucleuspb_state_proto_rawDescGZIP(), []int{2}
}

func (x *NucleusState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NucleusState) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *NucleusState) GetHoveredUnit() *HoveredUnit {
	if x != nil {
		return x.HoveredUnit
	}
	return nil
}

var File_nucleuspb_state_proto protoreflect.FileDescriptor

const file_nucleuspb_state_proto_rawDesc = "" +
	"\n" +
	"\x15nucleuspb/state.proto\x12\tnucleuspb\"T\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x89\x01\n" +
	"\vHoveredUnit\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tunit_type\x18\x03 \x01(\tR\bunitType\x12\x19\n" +
	"\bimg_path\x18\x04 \x01(\tR\aimgPath\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\"\x98\x01\n" +
	"\fNucleusState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12/\n" +
	"\bproposal\x18\x02 \x01(\v2\x13.nucleuspb.ProposalR\bproposal\x129\n" +
	"\fhovered_unit\x18\x03 \x01(\v2\x16.nucleuspb.HoveredUnitR\vhoveredUnitB.Z,github.com/50v3r31gn-m4ch1n4/crush/nucleuspbb\x06proto3"

var (
	file_nucleuspb_state_proto_rawDescOnce sync.Once
	file_nucleuspb_state_proto_rawDescData []byte
)

func file_nucleuspb_state_proto_rawDescGZIP() []byte {
	file_nucleuspb_state_proto_rawDescOnce.Do(func() {
		file_nucleuspb_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nucleuspb_state_proto_rawDesc), len(file_nucleuspb_state_proto_rawDesc)))
	})
	return file_nucleuspb_state_proto_rawDescData
}

var file_nucleuspb_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nucleuspb_state_proto_goTypes = []any{
	(*Proposal)(nil),     // 0: nucleuspb.Proposal
	(*HoveredUnit)(nil),  // 1: nucleuspb.HoveredUnit
	(*NucleusState)(nil), // 2: nucleuspb.NucleusState
}
var file_nucleuspb_state_proto_depIdxs = []int32{
	0, // 0: nucleuspb.NucleusState.proposal:type_name -> nucleuspb.Proposal
	1, // 1: nucleuspb.NucleusState.hovered_unit:type_name -> nucleuspb.HoveredUnit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nucleuspb_state_proto_init() }
func file_nucleuspb_state_proto_init() {
	if File_nucleuspb_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nucleuspb_state_proto_rawDesc), len(file_nucleuspb_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nucleuspb_state_proto_goTypes,
		DependencyIndexes: file_nucleuspb_state_proto_depIdxs,
		MessageInfos:      file_nucleuspb_state_proto_msgTypes,
	}.Build()
	File_nucleuspb_state_proto = out.File
	file_nucleuspb_state_proto_goTypes = nil
	file_nucleuspb_state_proto_depIdxs = nil
}
