// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v3.8.0
// 	protoc        v3.8.0
// source: crush/nucleuspb/state.proto

package nucleuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proposal mirrors the VSB pending-action struct from watcher.go.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_crush_nucleuspb_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_crush_nucleuspb_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_crush_nucleuspb_state_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// HoveredUnit mirrors the Mmap hovered-unit layout.
type HoveredUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UnitType      string                 `protobuf:"bytes,3,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	ImgPath       string                 `protobuf:"bytes,4,opt,name=img_path,json=imgPath,proto3" json:"img_path,omitempty"`
	X             float32                `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoveredUnit) Reset() {
	*x = HoveredUnit{}
	mi := &file_crush_nucleuspb_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoveredUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoveredUnit) ProtoMessage() {}

func (x *HoveredUnit) ProtoReflect() protoreflect.Message {
	mi := &file_crush_nucleuspb_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoveredUnit.ProtoReflect.Descriptor instead.
func (*HoveredUnit) Descriptor() ([]byte, []int) {
	return file_crush_nucleuspb_state_proto_rawDescGZIP(), []int{1}
}

func (x *HoveredUnit) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HoveredUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HoveredUnit) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *HoveredUnit) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

func (x *HoveredUnit) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HoveredUnit) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistrictId    string                 `protobuf:"bytes,2,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VendorName    string                 `protobuf:"bytes,3,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	ItemCount     uint32                 `protobuf:"varint,4,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_crush_nucleuspb_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_crush_nucleuspb_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_crush_nucleuspb_state_proto_rawDescGZIP(), []int{2}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

func (x *Market) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

func (x *Market) GetItemCount() uint32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cost          uint32                 `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_crush_nucleuspb_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_crush_nucleuspb_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_crush_nucleuspb_state_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// NucleusState is the VSB snapshot broadcast to all Nucleus Deck clients at ~60fps.
type NucleusState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposal      *Proposal              `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	HoveredUnit   *HoveredUnit           `protobuf:"bytes,3,opt,name=hovered_unit,json=hoveredUnit,proto3" json:"hovered_unit,omitempty"`
	Logs          []string               `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	Narrative     []string               `protobuf:"bytes,5,rep,name=narrative,proto3" json:"narrative,omitempty"`
	RecentMarkets []*Market              `protobuf:"bytes,6,rep,name=recent_markets,json=recentMarkets,proto3" json:"recent_markets,omitempty"`
	LexiconItems  []*Item                `protobuf:"bytes,7,rep,name=lexicon_items,json=lexiconItems,proto3" json:"lexicon_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NucleusState) Reset() {
	*x = NucleusState{}
	mi := &file_crush_nucleuspb_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NucleusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NucleusState) ProtoMessage() {}

func (x *NucleusState) ProtoReflect() protoreflect.Message {
	mi := &file_crush_nucleuspb_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NucleusState.ProtoReflect.Descriptor instead.
func (*NucleusState) Descriptor() ([]byte, []int) {
	return file_crush_nucleuspb_state_proto_rawDescGZIP(), []int{4}
}

func (x *NucleusState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NucleusState) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *NucleusState) GetHoveredUnit() *HoveredUnit {
	if x != nil {
		return x.HoveredUnit
	}
	return nil
}

func (x *NucleusState) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *NucleusState) GetNarrative() []string {
	if x != nil {
		return x.Narrative
	}
	return nil
}

func (x *NucleusState) GetRecentMarkets() []*Market {
	if x != nil {
		return x.RecentMarkets
	}
	return nil
}

func (x *NucleusState) GetLexiconItems() []*Item {
	if x != nil {
		return x.LexiconItems
	}
	return nil
}

var File_crush_nucleuspb_state_proto protoreflect.FileDescriptor

const file_crush_nucleuspb_state_proto_rawDesc = "" +
	"\n" +
	"\x1bcrush/nucleuspb/state.proto\x12\tnucleuspb\"T\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x89\x01\n" +
	"\vHoveredUnit\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tunit_type\x18\x03 \x01(\tR\bunitType\x12\x19\n" +
	"\bimg_path\x18\x04 \x01(\tR\aimgPath\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\"y\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdistrict_id\x18\x02 \x01(\tR\n" +
	"districtId\x12\x1f\n" +
	"\vvendor_name\x18\x03 \x01(\tR\n" +
	"vendorName\x12\x1d\n" +
	"\n" +
	"item_count\x18\x04 \x01(\rR\titemCount\"R\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\rR\x04cost\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xba\x02\n" +
	"\fNucleusState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12/\n" +
	"\bproposal\x18\x02 \x01(\v2\x13.nucleuspb.ProposalR\bproposal\x129\n" +
	"\fhovered_unit\x18\x03 \x01(\v2\x16.nucleuspb.HoveredUnitR\vhoveredUnit\x12\x12\n" +
	"\x04logs\x18\x04 \x03(\tR\x04logs\x12\x1c\n" +
	"\tnarrative\x18\x05 \x03(\tR\tnarrative\x128\n" +
	"\x0erecent_markets\x18\x06 \x03(\v2\x11.nucleuspb.MarketR\rrecentMarkets\x124\n" +
	"\rlexicon_items\x18\a \x03(\v2\x0f.nucleuspb.ItemR\flexiconItemsB.Z,github.com/50v3r31gn-m4ch1n4/crush/nucleuspbb\x06proto3"

var (
	file_crush_nucleuspb_state_proto_rawDescOnce sync.Once
	file_crush_nucleuspb_state_proto_rawDescData []byte
)

func file_crush_nucleuspb_state_proto_rawDescGZIP() []byte {
	file_crush_nucleuspb_state_proto_rawDescOnce.Do(func() {
		file_crush_nucleuspb_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crush_nucleuspb_state_proto_rawDesc), len(file_crush_nucleuspb_state_proto_rawDesc)))
	})
	return file_crush_nucleuspb_state_proto_rawDescData
}

var file_crush_nucleuspb_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crush_nucleuspb_state_proto_goTypes = []any{
	(*Proposal)(nil),     // 0: nucleuspb.Proposal
	(*HoveredUnit)(nil),  // 1: nucleuspb.HoveredUnit
	(*Market)(nil),       // 2: nucleuspb.Market
	(*Item)(nil),         // 3: nucleuspb.Item
	(*NucleusState)(nil), // 4: nucleuspb.NucleusState
}
var file_crush_nucleuspb_state_proto_depIdxs = []int32{
	0, // 0: nucleuspb.NucleusState.proposal:type_name -> nucleuspb.Proposal
	1, // 1: nucleuspb.NucleusState.hovered_unit:type_name -> nucleuspb.HoveredUnit
	2, // 2: nucleuspb.NucleusState.recent_markets:type_name -> nucleuspb.Market
	3, // 3: nucleuspb.NucleusState.lexicon_items:type_name -> nucleuspb.Item
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_crush_nucleuspb_state_proto_init() }
func file_crush_nucleuspb_state_proto_init() {
	if File_crush_nucleuspb_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crush_nucleuspb_state_proto_rawDesc), len(file_crush_nucleuspb_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crush_nucleuspb_state_proto_goTypes,
		DependencyIndexes: file_crush_nucleuspb_state_proto_depIdxs,
		MessageInfos:      file_crush_nucleuspb_state_proto_msgTypes,
	}.Build()
	File_crush_nucleuspb_state_proto = out.File
	file_crush_nucleuspb_state_proto_goTypes = nil
	file_crush_nucleuspb_state_proto_depIdxs = nil
}
