import fs from 'node:fs';
import path from 'node:path';

/**
 * SOVEREIGN_SDK_FORGE : v3.8.24-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS
 * 
 * Automatically generates TS/Go protocol shards from the Rust source of truth.
 * Prevents magic-number drift across the mesh.
 */

const RUST_SOURCE = 'crates/sovereign-sdk/src/protocol.rs';
const TS_TARGET   = 'packages/hermes-core/src/shared/protocol.ts';
const GO_TARGET   = 'crush/harness/protocol/generated_offsets.go';

function forge() {
    console.log('::/5Y573M-N071C3 : IGNITING_SDK_FORGE...');

    if (!fs.existsSync(RUST_SOURCE)) {
        console.error(`❌ [FORGE] Source not found: ${RUST_SOURCE}`);
        process.exit(1);
    }

    const content = fs.readFileSync(RUST_SOURCE, 'utf8');
    
    // Extract pub const VSB_... patterns
    const constRegex = /pub const (\w+):\s*(usize|u16|u8)\s*=\s*([\w\d]+);/g;
    let match;
    const constants: Record<string, string> = {};

    while ((match = constRegex.exec(content)) !== null) {
        constants[match[1]] = match[3];
    }

    // ─── Generate TS ─────────────────────────────────────────────────────────
    let tsContent = `/**\n * GENERATED BY SDK_FORGE — DO NOT EDIT MANUALLY\n * Source: ${RUST_SOURCE}\n */\n\n`;
    for (const [name, value] of Object.entries(constants)) {
        const tsValue = value.startsWith('0x') ? value : parseInt(value, 10);
        tsContent += `export const ${name} = ${tsValue};\n`;
    }
    fs.writeFileSync(TS_TARGET, tsContent);
    console.log(`● [FORGE] Shored TS: ${TS_TARGET}`);

    // ─── Generate Go ─────────────────────────────────────────────────────────
    let goContent = `package protocol\n\n/**\n * GENERATED BY SDK_FORGE — DO NOT EDIT MANUALLY\n * Source: ${RUST_SOURCE}\n */\n\nconst (\n`;
    for (const [name, value] of Object.entries(constants)) {
        goContent += `\t${name} = ${value}\n`;
    }
    goContent += `)\n`;
    fs.writeFileSync(GO_TARGET, goContent);
    console.log(`● [FORGE] Shored Go: ${GO_TARGET}`);

    console.log('::/5Y573M-N071C3 : FORGE_COMPLETE. PARITY_ACHIEVED.');
}

forge();
