/**
 * src/core/plugins/SkillAuthor.ts — Phase 87: Agentic Skill-Authoring
 *
 * Converts successful agent trajectories (recorded tool-call sequences) into
 * reusable `.ts` MCP tool files and registers them into the PluginRegistry.
 *
 * Workflow:
 *   1. Agent completes a successful trajectory and calls `SkillAuthor.ingest(trajectory)`
 *   2. SkillAuthor synthesises the pattern into a named TypeScript tool function
 *   3. The tool is written to `src/core/plugins/skills/<name>.ts`
 *   4. The tool is registered in the live PluginRegistry instance
 *
 * Tool output format:
 *   export const <name>Tool: McpTool = { name, description, inputSchema, handler }
 */

import { writeFile, mkdir, readdir } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { existsSync } from 'node:fs';
import type { PluginRegistry } from './PluginRegistry.js';
import { SteganoEncoder } from '../crypto/SteganoEncoder.js';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface TrajectoryStep {
  /** MCP tool name that was called */
  tool:    string;
  /** Input arguments passed to the tool */
  input:   Record<string, unknown>;
  /** Tool output (summary or truncated) */
  output:  string;
  /** Whether this step succeeded */
  success: boolean;
}

export interface AgentTrajectory {
  /** Human-readable goal description */
  goal:         string;
  /** Steps the agent took */
  steps:        TrajectoryStep[];
  /** Final outcome summary */
  outcome:      string;
  /** Whether the trajectory was successful overall */
  succeeded:    boolean;
  /** Timestamp (ISO 8601) */
  recorded_at:  string;
}

export interface SynthesisedSkill {
  /** camelCase function name */
  name:        string;
  description: string;
  /** TypeScript source of the generated tool */
  source:      string;
  /** Derived from the trajectory goal */
  capability:  string;
}

// ── SkillAuthor ───────────────────────────────────────────────────────────────

const SKILLS_DIR = join(process.cwd(), 'src/core/plugins/skills');

export class SkillAuthor {
  constructor(private readonly registry: PluginRegistry) {}

  /**
   * Ingests a successful agent trajectory, synthesises a skill, writes the
   * tool file and registers it into the live PluginRegistry.
   *
   * Silently no-ops on failed trajectories (only successful patterns promoted).
   */
  async ingest(trajectory: AgentTrajectory): Promise<SynthesisedSkill | null> {
    if (!trajectory.succeeded) return null;

    const skill = this.synthesise(trajectory);

    await mkdir(SKILLS_DIR, { recursive: true });
    const filePath = join(SKILLS_DIR, `${skill.name}.ts`);
    
    // Phase 89: Steganographic Proof Injection
    const proof = Buffer.from(skill.name).toString('base64');
    const finalSource = SteganoEncoder.injectProof(skill.source, proof);
    
    await writeFile(filePath, finalSource, 'utf-8');

    this.registry.register({
      id:          `skill:${skill.name}`,
      name:        skill.name,
      description: skill.description,
      author:      'SkillAuthor:auto',
      version:     '1.0.0',
      endpoints:   {},
      capabilities: [skill.capability],
    });

    console.log(`◈ [SkillAuthor] Materialised: ${skill.name} → ${filePath}`);
    return skill;
  }

  /**
   * Lists all auto-generated skills currently on disk.
   */
  async listSkills(): Promise<string[]> {
    if (!existsSync(SKILLS_DIR)) return [];
    const entries = await readdir(SKILLS_DIR);
    return entries.filter(f => f.endsWith('.ts')).map(f => basename(f, '.ts'));
  }

  // ── Synthesis ────────────────────────────────────────────────────────────────

  private synthesise(t: AgentTrajectory): SynthesisedSkill {
    const name       = goalToFunctionName(t.goal);
    const capability = deriveCapability(t.steps);
    const description = `Auto-synthesised from trajectory: "${t.goal}". Outcome: ${t.outcome}`;

    const stepDocs = t.steps
      .filter(s => s.success)
      .map((s, i) => `   * Step ${i + 1}: ${s.tool}(${JSON.stringify(s.input)})`)
      .join('\n');

    const handlerSteps = t.steps
      .filter(s => s.success)
      .map((s, i) =>
        `  // Step ${i + 1}: ${s.tool}\n  const _step${i + 1} = await callTool('${s.tool}', ${JSON.stringify(s.input, null, 2).replace(/\n/g, '\n  ')});`
      )
      .join('\n\n');

    const source = `/**
 * AUTO-GENERATED by SkillAuthor — do not edit manually.
 * Goal: ${t.goal}
 * Recorded: ${t.recorded_at}
 *
 * Trajectory (${t.steps.filter(s => s.success).length} steps):
${stepDocs}
 */

import type { McpTool } from '../../hermes/mcp-types.js';

// Tool-call helper — resolved at runtime via the active MCP session.
declare function callTool(name: string, args: Record<string, unknown>): Promise<unknown>;

export const ${name}Tool: McpTool = {
  name: '${name}',
  description: ${JSON.stringify(description)},
  inputSchema: {
    type: 'object',
    properties: {
      goal: { type: 'string', description: 'Override goal context for this invocation' },
    },
  },
  handler: async (_args: Record<string, unknown>) => {
${handlerSteps}

    return { success: true, outcome: ${JSON.stringify(t.outcome)} };
  },
};
`;

    return { name, description, source, capability };
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Converts a natural-language goal into a valid camelCase identifier. */
function goalToFunctionName(goal: string): string {
  return goal
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 5)                // max 5 words
    .map((w, i) => i === 0 ? w : w[0]!.toUpperCase() + w.slice(1))
    .join('') || 'autoSkill';
}

/** Heuristically derives a CAPABILITY tag from the tool names used. */
function deriveCapability(steps: TrajectoryStep[]): string {
  const tools = steps.map(s => s.tool.toLowerCase());
  if (tools.some(t => t.includes('memory') || t.includes('remember'))) return 'MEMORY_WRITE';
  if (tools.some(t => t.includes('search') || t.includes('query')))    return 'MEMORY_READ';
  if (tools.some(t => t.includes('notify') || t.includes('hud')))      return 'HUD_NOTIFY';
  if (tools.some(t => t.includes('spatial') || t.includes('3d')))      return 'SPATIAL_PROJECTION';
  return 'AGENT_ACTION';
}
