#!/usr/bin/env tsx
/**
 * scripts/forge/skill-factory.ts
 *
 * Phase 52.3: Skill Factory — Hermes Pattern
 *
 * Monitors .crush/logs/crush.log for repeated "Research → Strategy → Execution"
 * cycles. When a successful pattern is detected (configurable threshold),
 * autonomously generates a SKILL.md shard proposal in
 * .gemini/skills/<slug>/SKILL.md.proposed
 *
 * All proposals require human approval before they become active shards.
 * Approved skills are renamed from .proposed → SKILL.md.
 *
 * Usage:
 *   npx tsx scripts/forge/skill-factory.ts [--once] [--dry-run]
 *
 * Options:
 *   --once     Process existing log and exit (no watch)
 *   --dry-run  Print proposals without writing files
 */

import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

// ── Config ─────────────────────────────────────────────────────────────────────

const PROJECT_ROOT   = process.env['PROJECT_ROOT'] ?? process.cwd();
const CRUSH_LOG      = path.join(PROJECT_ROOT, '.crush/logs/crush.log');
const SKILLS_DIR     = path.join(PROJECT_ROOT, '.gemini/skills');
const FACTORY_LOG    = path.join(PROJECT_ROOT, 'data/logs/skill-factory.log');
const CYCLE_THRESHOLD = 2;      // min repetitions before generating a shard
const WATCH_INTERVAL  = 30_000; // ms — re-scan interval

// ── Types ──────────────────────────────────────────────────────────────────────

interface CrushLogLine {
  time:    string;
  level:   string;
  msg:     string;
  source?: { function?: string };
}

type CyclePhase = 'research' | 'strategy' | 'execution';

interface DetectedCycle {
  id:          string;
  name:        string;
  description: string;
  phases:      { phase: CyclePhase; msg: string; time: string }[];
  count:       number;
}

// ── Phase detection patterns ───────────────────────────────────────────────────

const PHASE_PATTERNS: Record<CyclePhase, RegExp[]> = {
  research: [
    /searching|analyzing|reviewing|fetching|reading|looking up|discovering|gathering/i,
    /research|investigate|explore|scan|audit|probe|inspect/i,
    /\bget\b.*\binfo\b|\bfetch\b.*\bdata\b|\bquery\b/i,
  ],
  strategy: [
    /planning|designing|architecting|deciding|choosing|selecting/i,
    /strategy|approach|implementation plan|will implement|proposed|going to/i,
    /steps:|workflow:|process:|1\.\s|phase \d/i,
  ],
  execution: [
    /completed|committed|shipped|deployed|built|created|implemented|done/i,
    /success|finished|✓|✅|pass|PASS/i,
    /git commit|git add|cargo build|npm run build|tsc/i,
  ],
};

function detectPhase(msg: string): CyclePhase | null {
  for (const [phase, patterns] of Object.entries(PHASE_PATTERNS) as [CyclePhase, RegExp[]][]) {
    if (patterns.some(r => r.test(msg))) return phase;
  }
  return null;
}

// ── Cycle extraction ──────────────────────────────────────────────────────────

function extractCycles(lines: CrushLogLine[]): Map<string, number> {
  const windowSize = 20; // lines to look ahead for a complete R→S→E cycle
  const cycleCounts = new Map<string, number>();

  for (let i = 0; i < lines.length - windowSize; i++) {
    const window = lines.slice(i, i + windowSize);
    let r: CrushLogLine | null = null;
    let s: CrushLogLine | null = null;
    let e: CrushLogLine | null = null;

    for (const line of window) {
      const p = detectPhase(line.msg);
      if (p === 'research' && !r) r = line;
      else if (p === 'strategy' && r && !s) s = line;
      else if (p === 'execution' && r && s && !e) { e = line; break; }
    }

    if (r && s && e) {
      // Generate a canonical key from the research message (normalised)
      const key = r.msg.toLowerCase().replace(/[^a-z0-9\s]/g, '').replace(/\s+/g, '-').slice(0, 40);
      cycleCounts.set(key, (cycleCounts.get(key) ?? 0) + 1);
    }
  }

  return cycleCounts;
}

// ── SKILL.md generation ───────────────────────────────────────────────────────

function toSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function generateSkillMd(cycle: DetectedCycle): string {
  const slug = toSlug(cycle.name);
  return `---
name: ${slug}
description: ${cycle.description}
---

# ${cycle.name}

> ⚠️ AUTO-GENERATED by Skill Factory (Phase 52.3). Review and approve before activating.
> Detected ${cycle.count} successful "Research → Strategy → Execution" cycles matching this pattern.

## Overview

This skill was distilled from repeated successful workflows observed in session logs.

## Workflow

### 1. Research Phase
Gather relevant context: search the codebase, consult the RKG oracle, or review prior session logs.

### 2. Strategy Phase
Synthesise findings into a concrete plan. Document the intended approach before writing code.

### 3. Execution Phase
Implement the plan in discrete, verifiable steps. Run \`npm run gauntlet\` after each batch.

## Activation

Rename \`SKILL.md.proposed\` to \`SKILL.md\` in \`.gemini/skills/${slug}/\` after human review.

*Generated: ${new Date().toISOString()} | ID: ${cycle.id}*
`;
}

// ── Writer ────────────────────────────────────────────────────────────────────

function writeProposal(cycle: DetectedCycle, dryRun: boolean): string {
  const slug    = toSlug(cycle.name);
  const dir     = path.join(SKILLS_DIR, slug);
  const outPath = path.join(dir, 'SKILL.md.proposed');

  if (dryRun) {
    return `[DRY-RUN] Would write: ${outPath}`;
  }

  fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(outPath)) {
    fs.writeFileSync(outPath, generateSkillMd(cycle));
    return `PROPOSED: ${outPath}`;
  }
  return `SKIPPED (already proposed): ${outPath}`;
}

function factoryLog(msg: string): void {
  const line = `[${new Date().toISOString()}] ${msg}\n`;
  process.stdout.write(line);
  try {
    fs.mkdirSync(path.dirname(FACTORY_LOG), { recursive: true });
    fs.appendFileSync(FACTORY_LOG, line);
  } catch { /* non-fatal */ }
}

// ── Main scan ─────────────────────────────────────────────────────────────────

function scan(dryRun: boolean): void {
  if (!fs.existsSync(CRUSH_LOG)) {
    factoryLog(`Crush log not found at ${CRUSH_LOG} — nothing to scan`);
    return;
  }

  const raw = fs.readFileSync(CRUSH_LOG, 'utf8');
  const lines: CrushLogLine[] = raw
    .split('\n')
    .filter(Boolean)
    .flatMap(l => {
      try { return [JSON.parse(l) as CrushLogLine]; }
      catch { return []; }
    });

  const cycleCounts = extractCycles(lines);
  let generated = 0;

  for (const [key, count] of cycleCounts.entries()) {
    if (count < CYCLE_THRESHOLD) continue;

    const name = key.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const cycle: DetectedCycle = {
      id:          randomUUID(),
      name,
      description: `Automated skill for "${name}" pattern (${count} successful cycles detected)`,
      phases:      [],
      count,
    };

    const result = writeProposal(cycle, dryRun);
    factoryLog(result);
    generated++;
  }

  factoryLog(`Scan complete — ${cycleCounts.size} patterns, ${generated} proposals generated`);
}

// ── Entry point ───────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const once   = args.includes('--once');
const dryRun = args.includes('--dry-run');

factoryLog(`Skill Factory started — threshold=${CYCLE_THRESHOLD} cycles, watch=${!once}, dry-run=${dryRun}`);
scan(dryRun);

if (!once) {
  setInterval(() => scan(dryRun), WATCH_INTERVAL);
  process.on('SIGTERM', () => process.exit(0));
  process.on('SIGINT',  () => process.exit(0));
}
