name: terminal_app
description: 50V3R31GN-M4CH1N4 Machina Terminal HUD
publish_to: 'none'

version: 3.2.21+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
