/**
 * GENERATED BY SDK_FORGE — DO NOT EDIT MANUALLY
 * Source: sovereign-sdk/src/protocol.rs
 */

export const VSB_MAGIC = 0xC0DE;
export const VSB_VERSION = 0x01;
export const RADAR_HEADER_SIZE = 24;
export const RADAR_BLIP_SIZE = 64;
export const GHOST_HEADER_SIZE = 20;
export const GHOST_BLIP_SIZE = 9;
export const VSB_MAP_SIZE = 4096;
export const VSB_MMAP_MAGIC_OFFSET = 0;
export const VSB_SOVEREIGN_MODE_OFFSET = 2048;
export const VSB_RADAR_OFFSET = 3072;
export const VSB_RADAR_SIZE = 3;
export const VSB_HOVERED_UNIT_OFFSET = 3205;
export const VSB_HOVERED_UNIT_SIZE = 133;
export const VSB_IDENTITY_SWITCH_OFFSET = 3338;
export const VSB_IDENTITY_SWITCH_SIZE = 65;
export const PROPOSAL_OFFSET = 1024;
export const CAPABILITY_OFFSET = 8192;
