#!/usr/bin/env tsx
/**
 * scripts/dev/hermes-wiki-sync.ts
 *
 * Phase 63.5 — Hermes-Wiki Auto-Documentation Daemon
 *
 * Polls Akashik.db for notable entities (items, actors, districts, events)
 * and materialises human-readable Markdown shards in docs/raw_data/.
 * Keeps the Obsidian vault and the RKG in bit-identical sync.
 *
 * Run:  nix develop --command tsx scripts/dev/hermes-wiki-sync.ts
 * Env:  AKASHIK_DB_PATH  (default: data/Akashik.db)
 *       WIKI_OUTPUT_DIR  (default: docs/raw_data/wiki)
 *       POLL_INTERVAL_MS (default: 60000)
 */

import { DatabaseSync } from 'node:sqlite';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const DB_PATH      = resolve(process.env.AKASHIK_DB_PATH  ?? 'data/Akashik.db');
const OUTPUT_DIR   = resolve(process.env.WIKI_OUTPUT_DIR  ?? 'docs/raw_data/wiki');
const POLL_MS      = parseInt(process.env.POLL_INTERVAL_MS ?? '60000', 10);

// ---------------------------------------------------------------------------
// DB query helpers
// ---------------------------------------------------------------------------

interface ItemRow {
  id: string;
  name: string;
  type: string;
  rarity: string | null;
  cost: number | null;
  description: string | null;
}

interface ActorRow {
  id: string;
  name: string;
  role: string | null;
  humanity: number | null;
  emp: number | null;
}

function queryItems(db: DatabaseSync): ItemRow[] {
  try {
    return db.prepare(
      'SELECT id, name, type, rarity, cost, description FROM items ORDER BY type, name LIMIT 500'
    ).all() as ItemRow[];
  } catch { return []; }
}

function queryActors(db: DatabaseSync): ActorRow[] {
  try {
    return db.prepare(
      'SELECT id, name, role, humanity, emp FROM actors ORDER BY name LIMIT 200'
    ).all() as ActorRow[];
  } catch { return []; }
}

// ---------------------------------------------------------------------------
// Markdown serialisers
// ---------------------------------------------------------------------------

function renderItems(items: ItemRow[]): string {
  const byType = items.reduce<Record<string, ItemRow[]>>((acc, item) => {
    (acc[item.type] ??= []).push(item);
    return acc;
  }, {});

  const lines = [
    `# Item Lexicon`,
    `> Auto-generated by Hermes-Wiki Sync — do not edit manually.`,
    `> Last sync: ${new Date().toISOString()}`,
    '',
  ];

  for (const [type, entries] of Object.entries(byType)) {
    lines.push(`## ${type.toUpperCase()}`);
    lines.push('');
    for (const item of entries) {
      lines.push(`### ${item.name}`);
      if (item.rarity) lines.push(`**Rarity:** ${item.rarity}`);
      if (item.cost != null) lines.push(`**Cost:** ${item.cost}eb`);
      if (item.description) lines.push(``, item.description);
      lines.push('');
    }
  }

  return lines.join('\n');
}

function renderActors(actors: ActorRow[]): string {
  const lines = [
    `# Actor Registry`,
    `> Auto-generated by Hermes-Wiki Sync — do not edit manually.`,
    `> Last sync: ${new Date().toISOString()}`,
    '',
  ];

  for (const actor of actors) {
    lines.push(`## ${actor.name}`);
    if (actor.role) lines.push(`**Role:** ${actor.role}`);
    if (actor.emp != null) lines.push(`**EMP:** ${actor.emp}`);
    if (actor.humanity != null) lines.push(`**Humanity:** ${actor.humanity}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Sync cycle
// ---------------------------------------------------------------------------

function syncCycle(): void {
  let db: DatabaseSync;
  try {
    db = new DatabaseSync(DB_PATH, { readonly: true });
  } catch (err) {
    process.stderr.write(`[hermes-wiki] DB open failed: ${err}\n`);
    return;
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const items  = queryItems(db);
  const actors = queryActors(db);

  if (items.length > 0) {
    writeFileSync(join(OUTPUT_DIR, 'item-lexicon.md'), renderItems(items), 'utf8');
    process.stderr.write(`[hermes-wiki] Wrote ${items.length} items → item-lexicon.md\n`);
  }

  if (actors.length > 0) {
    writeFileSync(join(OUTPUT_DIR, 'actor-registry.md'), renderActors(actors), 'utf8');
    process.stderr.write(`[hermes-wiki] Wrote ${actors.length} actors → actor-registry.md\n`);
  }

  db.close();
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

process.stderr.write(`[hermes-wiki] Daemon started. DB=${DB_PATH} OUT=${OUTPUT_DIR} POLL=${POLL_MS}ms\n`);
syncCycle();
setInterval(syncCycle, POLL_MS);
