import { Database } from "bun:sqlite";
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * SOVEREIGN GRUVBOX V1.0 - SEMANTIC RETRIEVAL BRIDGE
 * Queries the Cold Archive and materializes a "Lore Brief" in the Hot Vault.
 */

const DB_PATH = "data/SovereignIntelligence.db";
const ARCHIVE_PATH = "/mnt/d/Obsidian_CPR_ColdStorage/Lore";
const TRANSIENT_PATH = "data/vault/RKG/Transient/lore-brief.md";

async function queryColdLore(query: string) {
    console.log(`◈ [BRIDGE] Querying Cold Shards for: "${query}"...`);

    const db = new Database(DB_PATH);
    
    // In production, this uses sqlite-vec semantic search.
    // For this pass, we perform a high-fidelity keyword match across os_triplets.
    const results = db.query(`
        SELECT subject_id, object_literal FROM os_triplets 
        WHERE predicate = 'LORE_SHARD' 
        AND (subject_id LIKE $query OR object_literal LIKE $query)
        LIMIT 5
    `).all({ $query: `%${query}%` }) as { subject_id: string, object_literal: string }[];

    if (results.length === 0) {
        console.log("◈ [BRIDGE] No matching shards found in Cold Storage.");
        return;
    }

    let briefContent = `# ◈ LORE BRIEF: ${query.toUpperCase()}\n\n`;
    briefContent += `*Generated by Sovereign Oracle v3.8.26-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS-SYNTHESIS*\n\n---\n\n`;

    for (const res of results) {
        briefContent += `### ◈ ${res.subject_id}\n${res.object_literal}\n\n`;
    }


    briefContent += `---\n**::/5Y573M-N071C3 : VEC70R_MA7ER14L1ZED. // 50V3R31GN-M4CH1N4**`;

    // Ensure Transient directory exists
    const dir = path.dirname(TRANSIENT_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(TRANSIENT_PATH, briefContent);
    console.log(`◈ [BRIDGE] Lore materialized at: ${TRANSIENT_PATH}`);
}

const args = process.argv.slice(2);
if (args.length > 0) {
    queryColdLore(args.join(" "));
} else {
    console.log("Usage: bun scripts/dev/query-cold-lore.ts <query>");
}
